package com.evgateway.server.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address")
@JsonIgnoreProperties(ignoreUnknown = true, value = { "user" })
public class Address extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String country;
	private String phone;
	private String state;
	private String secondaryPhone;

	private String zipCode;
	private User user;
	private String uid;
	private String countryCode;
	private String secondaryCountryCode;

	public Address() {
	}

	public Address(User user, String addressLine2, String city, String country, String phone, String state,
			String addressLine1, String zipCode, String secondaryPhone, String countryCode,
			String secondaryCountryCode) {
		this.user = user;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.state = state;
		this.addressLine1 = addressLine1;
		this.zipCode = zipCode;
		this.secondaryPhone = secondaryPhone;
		this.countryCode = countryCode;
		this.secondaryCountryCode = secondaryCountryCode;

	}

	public Address(Long id, String addressLine2, String city, String country, String phone, String state,
			String addressLine1, String zipCode) {
		this.id = id;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.state = state;
		this.addressLine1 = addressLine1;
		this.zipCode = zipCode;
	}

	public Address(User user, String phone) {
		this.user = user;
		this.phone = phone;
	}

	public Address(User user, String addressLine2, String city, String country, String phone, String state,
			String addressLine1, String zipCode) {
		this.user = user;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.state = state;
		this.addressLine1 = addressLine1;
		this.zipCode = zipCode;
		
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity = User.class)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "addressLine2", length = 50)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		if (phone == null)
			phone = "";
		this.phone = phone;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "addressLine1", length = 50)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "zipCode")
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getSecondaryPhone() {
		return secondaryPhone;
	}

	public void setSecondaryPhone(String secondaryPhone) {
		this.secondaryPhone = secondaryPhone;
	}

	@Column(name = "countryCode")
	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Override
	public String toString() {
		return "Address [addressLine1=" + addressLine1 + ", addressLine2=" + addressLine2 + ", city=" + city
				+ ", country=" + country + ", phone=" + phone + ", state=" + state + ", secondaryPhone="
				+ secondaryPhone + ", zipCode=" + zipCode + ", user=" + user + ", uid=" + uid + ", countryCode="
				+ countryCode + ", secondaryCountryCode=" + secondaryCountryCode + "]";
	}

	public String getSecondaryCountryCode() {
		return secondaryCountryCode;
	}

	public void setSecondaryCountryCode(String secondaryCountryCode) {
		this.secondaryCountryCode = secondaryCountryCode;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

}
