package com.evgateway.server.pojo;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile")
@JsonIgnoreProperties(ignoreUnknown = true, value = { "user" })
public class Profile extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3911808774001932243L;

	private String status;

	private User user;
	private Language lang;
	private Zone zone;
	private String otp;

	private String uid;
	private Country country;
	private boolean istwofa;



	@Transient
	private String countryCode;

	public Profile() {
	}

	public Profile(String status, User user, Language lang, Zone zone, String otp, String countryCode) {
		super();
		this.status = status;
		this.user = user;
		this.lang = lang;
		this.zone = zone;
		this.otp = otp;

	
		this.countryCode = countryCode;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@JoinColumn(name = "lang_id")
	@ManyToOne(fetch = FetchType.EAGER)
	public Language getLang() {
		return lang;
	}

	public void setLang(Language lang) {
		this.lang = lang;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "zone_id")
	public Zone getZone() {
		return zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public String getOtp() {
		return otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@JoinColumn(name = "country_id")
	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	

	@Transient
	public String getCountryCode() {
		return countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "istwofa", columnDefinition = "double precision default 0 not null")
	public boolean isIstwofa() {
		return istwofa;
	}

	public void setIstwofa(boolean istwofa) {
		this.istwofa = istwofa;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Override
	public String toString() {
		return "Profile [status=" + status + ", user=" + user + ", lang=" + lang + ", zone=" + zone + ", otp=" + otp
				+ ", uid=" + uid + ", country=" + country + ", istwofa=" + istwofa
				+ ", countryCode=" + countryCode + "]";
	}

}
