package com.evgateway.server.pojo;

import java.util.Arrays;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Site generated by hbm2java
 */
@Entity
@Table(name = "promoCode")
public class PromoCode extends BaseEntity {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String manufracturer;

	private double amount;
	private String amountType;
	private boolean neverExpired;
	private String promoCodeType;
	private long noOfUsage;
	private long orgId;
	// private String userId;
	private Date expiryDate;
	@Temporal(TemporalType.DATE)
	@Column(name = "creationDate", length = 10)
	private Date creationDate;
	private Date modifiedDate;
	private String createdBy;
	private String ModifiedBy;

	

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getBussinessName() {
		return bussinessName;
	}

	public void setBussinessName(String bussinessName) {
		this.bussinessName = bussinessName;
	}

	public String getTimeType() {
		return timeType;
	}

	public void setTimeType(String timeType) {
		this.timeType = timeType;
	}

	public Long getTime() {
		return time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	private String[] codes;

	private String pname;

	private String bussinessName;

	private String timeType;

	private Long time;

	@Transient
	public String[] getCodes() {
		return codes;
	}

	public void setCodes(String[] codes) {
		this.codes = codes;
	}

	public String getManufracturer() {
		return manufracturer;
	}

	public void setManufracturer(String manufracturer) {
		this.manufracturer = manufracturer;
	}

	

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	/*
	 * public String getUserId() { return userId; } public void setUserId(String
	 * userId) { this.userId = userId; }
	 */
	public Date getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getModifiedBy() {
		return ModifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		ModifiedBy = modifiedBy;
	}

	public String getAmountType() {
		return amountType;
	}

	public void setAmountType(String amountType) {
		this.amountType = amountType;
	}

	public String getPromoCodeType() {
		return promoCodeType;
	}

	public void setPromoCodeType(String promoCodeType) {
		this.promoCodeType = promoCodeType;
	}

//	}
	public long getOrgId() {
		return orgId;
	}

	public void setOrgId(long orgId) {
		this.orgId = orgId;
	}

	public boolean isNeverExpired() {
		return neverExpired;
	}

	public void setNeverExpired(boolean neverExpired) {
		this.neverExpired = neverExpired;
	}

	public long getNoOfUsage() {
		return noOfUsage;
	}

	public void setNoOfUsage(long noOfUsage) {
		this.noOfUsage = noOfUsage;
	}

	@Override
	public String toString() {
		return "PromoCode [manufracturer=" + manufracturer + ", amount=" + amount + ", amountType="
				+ amountType + ", neverExpired=" + neverExpired + ", promoCodeType=" + promoCodeType + ", noOfUsage="
				+ noOfUsage + ", orgId=" + orgId + ", expiryDate=" + expiryDate + ", creationDate=" + creationDate
				+ ", modifiedDate=" + modifiedDate + ", createdBy=" + createdBy + ", ModifiedBy=" + ModifiedBy
				+ ", codes=" + Arrays.toString(codes) + ", pname=" + pname + ", bussinessName=" + bussinessName
				+ ", timeType=" + timeType + ", time=" + time + "]";
	}

}