name: Build and Deploy to AKS

on:
  push:
    branches:
      - testing   # Change to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Create this secret in GitHub with your Azure Service Principal JSON

      # 3. Log in to Azure Container Registry
      - name: Azure ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}
        # secrets.ACR_NAME = your ACR name (e.g., myregistry123)

      # 4. Build & Push Docker Image to ACR
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/driverserver:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      # 5. Set AKS Context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name: ${{ secrets.AKS_CLUSTER }}

      # 6. Update Kubernetes manifest with new image
      - name: Update image in deploy.yml
