---
apiVersion: v1
kind: ConfigMap
metadata:
  name: driverserver-config
data:
  DB_HOST: "sqlserver.default.svc.cluster.local"
  DB_PORT: "1433"
  DB_NAME: "driversdb"
  SPRING_PROFILES_ACTIVE: "prod"

---
apiVersion: v1
kind: Secret
metadata:
  name: driverserver-secret
type: Opaque
stringData:
  DB_USERNAME: "your_db_user"
  DB_PASSWORD: "your_db_password"
  JWT_SECRET: "your_jwt_secret_key"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driverserver
  labels:
    app: driverserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: driverserver
  template:
    metadata:
      labels:
        app: driverserver
    spec:
      containers:
      - name: driverserver
        image: evgacr.azurecr.io/driverserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: driverserver-config
        - secretRef:
            name: driverserver-secret
---
apiVersion: v1
kind: Service
metadata:
  name: driverserver-service
spec:
  selector:
    app: driverserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
